/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const VitalsReading = IDL.Record({
  'respiratoryRate' : IDL.Float64,
  'temperature' : IDL.Float64,
  'spo2' : IDL.Float64,
  'systolicBP' : IDL.Float64,
  'diastolicBP' : IDL.Float64,
  'heartRate' : IDL.Float64,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addSimulatedReading' : IDL.Func([VitalsReading], [], []),
  'addVitalsReading' : IDL.Func(
      [
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'getAllReadings' : IDL.Func([], [IDL.Vec(VitalsReading)], ['query']),
  'getLatestReading' : IDL.Func([], [VitalsReading], ['query']),
  'getReadingsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(VitalsReading)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const VitalsReading = IDL.Record({
    'respiratoryRate' : IDL.Float64,
    'temperature' : IDL.Float64,
    'spo2' : IDL.Float64,
    'systolicBP' : IDL.Float64,
    'diastolicBP' : IDL.Float64,
    'heartRate' : IDL.Float64,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addSimulatedReading' : IDL.Func([VitalsReading], [], []),
    'addVitalsReading' : IDL.Func(
        [
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'getAllReadings' : IDL.Func([], [IDL.Vec(VitalsReading)], ['query']),
    'getLatestReading' : IDL.Func([], [VitalsReading], ['query']),
    'getReadingsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(VitalsReading)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };